// src/styles.js
export const styles = {
    container: { fontFamily: "'Sarabun', sans-serif", background: 'linear-gradient(135deg, #fdf2f8 0%, #f5f3ff 100%)', minHeight: '100vh', padding: '2rem' },
    header: { textAlign: 'center', marginBottom: '2rem', color: '#1e293b' },
    progressContainer: { maxWidth: '600px', margin: '0 auto 2rem auto' },
    progressBar: { width: '100%', height: '8px', background: '#e5e7eb', borderRadius: '4px', overflow: 'hidden' },
    progressFill: { height: '100%', background: 'linear-gradient(90deg, #db2777 0%, #9333ea 100%)', transition: 'width 0.4s ease-in-out' },
    card: { maxWidth: '600px', margin: '0 auto', background: 'white', borderRadius: '1rem', boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1)', padding: '2rem' },
    welcome: { textAlign: 'center', padding: '2rem 0' },
    options: { display: 'flex', flexDirection: 'column', gap: '0.75rem', margin: '1.5rem 0' },
    btnOption: { padding: '1rem', border: '1px solid #d1d5db', background: 'white', borderRadius: '0.75rem', cursor: 'pointer', textAlign: 'left', fontSize: '1rem', transition: 'all 0.2s ease', color: '#374151' },
    btnPrimary: { flex: 1, padding: '0.75rem 1.5rem', background: 'linear-gradient(90deg, #db2777 0%, #9333ea 100%)', color: 'white', border: 'none', borderRadius: '0.75rem', fontSize: '1rem', fontWeight: '600', cursor: 'pointer' },
    btnBack: { flex: 1, padding: '0.75rem 1.5rem', background: 'transparent', color: '#6b7280', border: '1px solid #d1d5db', borderRadius: '0.75rem', fontSize: '1rem', fontWeight: '600', cursor: 'pointer' },
    navigation: { display: 'flex', gap: '1rem', marginTop: '1.5rem' },
    productCard: { border: '1px solid #e5e7eb', background: '#fafafa', padding: '1rem', borderRadius: '0.75rem', display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1rem' },
    rank: { fontSize: '1.75rem', color: '#6b7280' },
    productInfo: { flex: 1 },
    productName: { fontWeight: '600', color: '#1f293b' },
    productDetail: { fontSize: '0.875rem', color: '#6b7280', marginTop: '0.25rem' },
    productPriceContainer: { textAlign: 'right' },
    productPrice: { fontWeight: 'bold', fontSize: '1.125rem', color: '#db2777' },
    productScore: { fontSize: '0.75rem', color: '#9333ea', marginTop: '0.25rem' },
    noProducts: { textAlign: 'center', padding: '3rem 1rem', color: '#6b7280' },
    footer: { textAlign: 'center', marginTop: '3rem', color: '#9ca3af', fontSize: '0.875rem' },
};